### ISSUE TITLE
concurrency issues. Summon jobs can block tenant loading

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/scheduler#120]
### present:
```
run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator
  config:
    max_concurrent_runs: 2
```

### future
Use asset based concurrency
https://docs.dagster.io/guides/limiting-concurrency-in-data-pipelines#limiting-concurrency-using-tags
