### ISSUE TITLE
rebuild namesspace fails with all

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/scheduler#181]
If the source list in a tenant is all

```
  - community: geocodesall
    hostname: geocodes-all
    description: GeoCodes is...
    name: Geocodes Science on Schema
    url: https://www.earthcube.org
    logo: https://unsplash.com/random
    graph:
      main_namespace: geocodes_test
      summary_namespace: geocodes_test_summary
    sources:
      - all
```

the rebuild namespace fails

`Failed to load release for all to tenant geocodesall https://graph.geocodes-aws.earthcube.org/blazegraph/namespace/geocodes_test/sparql:  graph: failed,  LOAD from https://oss.geocodes-aws.earthcube.org:443/decoder/graphs/latest/all_release.nq: status:500`
