### ISSUE TITLE
Production and Multiple Deployments

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/scheduler#26]
# Stabilize a branch for use as 'production'
* create production branch, add to workflow... then configure dagster stack.
*  Slow changing of generated code

# Multiple deployment of same PROJECT to same portainer
 need to separate the PROJECT from the deployment.  Right now, PROJECT is part of traefik labels, and PROJECT generates the code.
Let's change to DAG_PROJECT

Add DAG_DEPLOY variable so that we can deploy multiple dagsters on same portainer for same project.
*  use that in traefik labels. Maybe maybe container names. 
* the NETWORK and VOLUME shared with gleaner/nabu will need to be named for each 'stack'
*  Will need it's own network, so that it does not get confused (aka same containers on same network with same name...)
```
  dagster_host:
    driver: overlay
    # using project name is a bit tricky from dagster code, and needs to be external for a
    # container to use them
    #name: dagster-${DAG_DEPLOY:-eco}
    name: dagster_host
    attachable: true
```
* volume.. 
    It think the postgres local volume is ok. It's defined as part of the stack, each stack separate
```
  dagster-project:
    external: true
    #name: dagster-${DAG_DEPLOY:-eco}
    name: dagster_gleaner_configs

```
