### ISSUE TITLE
Docker Compose Networking and added headless

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/scheduler#4]
added a dagster_host network, so jus the dagster containers talk to each other.
added headless to the dagster to see if it can be configured to be access to this stack.

```
networks:
  traefik_proxy:
    external: true
  dagster_host:
    driver: overlay
    name: dagster-${PROJECT}
    attachable: true
```

```
    headless:
      image: chromedp/headless-shell:latest
  #    build:
  #      context: .
  #      shm_size: "2gb"
      restart: unless-stopped
      shm_size: "2gb"
      labels:
        - "traefik.backend=headlesschrome"
        - "traefik.port=9222"
      ports:
        - 9222:9222
      environment:
        - SERVICE_PORTS=9222
      networks:
        - dagster_host
```
